# Generated by Django 4.0.3 on 2022-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
