# Generated by Django 4.0.3 on 2022-05-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_branch_userprofile_branch'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
