# Generated by Django 4.0.3 on 2022-05-19 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_skillset_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillset',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_skill', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
