# Generated by Django 4.0.3 on 2022-05-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_field', models.CharField(choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], max_length=255)),
                ('job_type', models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Internship')], null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('yrs_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Received'), (2, 'Awaiting Placement'), (3, 'Placed')], null=True)),
                ('payment_budget', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('desciption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cv', models.FileField(upload_to='cv/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_job_application', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'job_application',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_field', models.CharField(choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], max_length=255)),
                ('job_type', models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Internship')], null=True)),
                ('highest_qualification', models.CharField(blank=True, max_length=250, null=True)),
                ('yrs_of_experience', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Received'), (2, 'Awaiting Placement'), (3, 'Placed')], null=True)),
                ('payment_budget', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('desciption', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_em_application', to='accounts.userprofile')),
            ],
            options={
                'db_table': 'employer_application',
                'ordering': ['-created_at'],
            },
        ),
    ]
