# Generated by Django 4.0.3 on 2022-05-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerapplication',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Internship')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Internship')], default=1),
            preserve_default=False,
        ),
    ]
