# Generated by Django 4.0.3 on 2022-05-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_employerapplication_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerapplication',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Internship')], null=True),
        ),
        migrations.AlterField(
            model_name='employerapplication',
            name='payment_budget',
            field=models.CharField(choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerapplication',
            name='related_field',
            field=models.CharField(choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], max_length=255),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_type',
            field=models.IntegerField(choices=[(1, 'Full-time'), (2, 'Part-time'), (3, 'Internship')], null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='payment_budget',
            field=models.CharField(choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='related_field',
            field=models.CharField(choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], max_length=255),
        ),
    ]
