# Generated by Django 4.0.3 on 2022-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_employerapplication_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerapplication',
            name='payment_budget',
            field=models.CharField(blank=True, choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='payment_budget',
            field=models.CharField(blank=True, choices=[('computer science', 'computer science'), ('information technology', 'information Technology'), ('networking', 'Networking'), ('fashion', 'Fashion'), ('hardware', 'Hardware'), ('graphic design', 'Graphic Design'), ('graph', 'Graphic Design')], max_length=255, null=True),
        ),
    ]
