# Generated by Django 4.0.3 on 2022-05-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_employerapplication_payment_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='cv',
            field=models.FileField(upload_to='cv/'),
        ),
    ]
