# Generated by Django 4.0.3 on 2022-05-17 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employerapplication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at']},
        ),
    ]
